### ISSUE TITLE
SQL error on quick edit

### ISSUE THREAD

**Issue by Poil** [mistic100/Piwigo-PhotoSphere#15]
Hi,

When quick editing a photo (to change date) and saving I have this SQL Error

```
 Fatal error: Uncaught mysqli_sql_exception: Incorrect integer value: '' for column `piwigo`.`piwigo_images`.`is_sphere` at row 1 in /srv/photos/www/piwigo/include/dblayer/functions_mysqli.inc.php:132 Stack trace: #0 /srv/photos/www/piwigo/include/dblayer/functions_mysqli.inc.php(132): mysqli->query() #1 /srv/photos/www/piwigo/include/dblayer/functions_mysqli.inc.php(478): pwg_query() #2 /srv/photos/www/piwigo/plugins/PhotoSphere/include/public_events.inc.php(117): single_update() #3 /srv/photos/www/piwigo/include/functions_plugins.inc.php(264): photosphere_save_admintools() #4 /srv/photos/www/piwigo/picture.php(137): trigger_notify() #5 {main} thrown in /srv/photos/www/piwigo/include/dblayer/functions_mysqli.inc.php on line 132
```

Best regards

**Comment by mistic100** [comment]
Version 0.2.5 released
